services:
  # =============== BACKEND SERVICE ===============
  - type: web
    name: donation-backend-kupat-hair
    runtime: node
    plan: free
    
    rootDir: server
    buildCommand: npm install
    startCommand: npm start
    
    envVars:
      - key: PORT
        value: "3000"
      - key: JWT_SECRET
        sync: false
      - key: HOST
        value: bxwrlqsqovxxehmmliip-mysql.services.clever-cloud.com
      - key: USER
        value: u5cgeo20ueytmpmf
      - key: PASSWORD
        sync: false
      - key: DATABASE
        value: bxwrlqsqovxxehmmliip
      - key: BANK_RATES_API_KEY
        value: https://edge.boi.gov.il/FusionEdgeServer/sdmx/v2/data/dataflow/BOI.STATISTICS/EXR/1.0/?c%5BSERIES_CODE%5D=RER_USD_ILS,RER_EUR_ILS&lastNObservations=1&format=sdmx-json

  # =============== FRONTEND SERVICE ===============
  - type: web
    name: donation-management-kupat-hair
    runtime: node
    plan: free
    
    rootDir: client
    buildCommand: npm install && npm run build
    startCommand: npx serve -s dist -l 5173
    
    envVars:
      - key: VITE_APP_API_URL
        value: https://donation-backend-kupat-hair.onrender.com/api
      - key: VITE_APP_API_TIMEOUT
        value: "10000"
